<?php
$a_capcodes = array();
$a_capcodes[1500500] = array('label'=>'Kazernealarm Archipel', 'lat' => 52.087678, 'lon' => 4.299481);
$a_capcodes[1500501] = array('label'=>'Kazernealarm Centrum', 'lat' => 52.074408, 'lon' => 4.294377);
$a_capcodes[1500502] = array('label'=>'Kazernealarm Escamp', 'lat' => 52.057239, 'lon' => 4.309762);
$a_capcodes[1500503] = array('label'=>'Lichtkrant Haagse Hout', 'lat' => 52.086673, 'lon' => 4.355682);
$a_capcodes[1500504] = array('label'=>'Kazernealarm Leidschenveen', 'lat' => 52.055914, 'lon' => 4.395454);
$a_capcodes[1500505] = array('label'=>'Kazernealarm Loosduinen', 'lat' => 52.053482, 'lon' => 4.257212);
$a_capcodes[1500506] = array('label'=>'Kazernealarm Scheveningen', 'lat' => 52.102088, 'lon' => 4.273630);
$a_capcodes[1500509] = array('label'=>'Lichtkrant Den Hoorn', 'lat' => 51.998991, 'lon' => 4.328515);
$a_capcodes[1500510] = array('label'=>'Lichtkrant Schipluiden', 'lat' => 51.979200, 'lon' => 4.319428);
$a_capcodes[1500511] = array('label'=>'Lichtkrant Maasland', 'lat' => 51.934837, 'lon' => 4.270290);
$a_capcodes[1500512] = array('label'=>'Lichtkrant Naaldwijk', 'lat' => 51.990647, 'lon' => 4.202112);
$a_capcodes[1500513] = array('label'=>'Lichtkrant Honselersdijk', 'lat' => 52.009062, 'lon' => 4.220678);
$a_capcodes[1500514] = array('label'=>'Lichtkrant Maasdijk', 'lat' => 51.960770, 'lon' => 4.207633);
$a_capcodes[1500515] = array('label'=>'Lichtkrant Monster', 'lat' => 52.021847, 'lon' => 4.180934);
$a_capcodes[1500516] = array('label'=>'Lichtkrant De Lier', 'lat' => 51.972754, 'lon' => 4.254530);
$a_capcodes[1500517] = array('label'=>'Lichtkrant \'s-Gravenzande', 'lat' => 51.996098, 'lon' => 4.178567);
$a_capcodes[1500518] = array('label'=>'Lichtkrant Wateringen', 'lat' => 52.022115, 'lon' => 4.275502);
$a_capcodes[1500519] = array('label'=>'Lichtkrant Delft', 'lat' => 52.003719, 'lon' => 4.351467);
$a_capcodes[1500520] = array('label'=>'Lichtkrant Pijnacker', 'lat' => 52.019677, 'lon' => 4.425876);
$a_capcodes[1500521] = array('label'=>'Lichtkrant Nootdorp', 'lat' => 52.019677, 'lon' => 4.425876);
$a_capcodes[1500522] = array('label'=>'Lichtkrant Leidschendam - Voorburg', 'lat' => 52.088083, 'lon' => 4.376282); //
$a_capcodes[1500523] = array('label'=>'Lichtkrant Rijswijk', 'lat' => 52.046561, 'lon' => 4.333806);
$a_capcodes[1500524] = array('label'=>'Lichtkrant Wassenaar', 'lat' => 52.145140, 'lon' => 4.398264);
$a_capcodes[1500525] = array('label'=>'Lichtkrant Oosterheem', 'lat' => 52.054025, 'lon' => 4.526690);
$a_capcodes[1500526] = array('label'=>'Lichtkrant Stadshart', 'lat' => 52.062057, 'lon' => 4.487701);

$call_keywords = array(
    'stationsgebouw',
    'parnassia',
    'lekkage',
    'winkel',
    'museum',
    'ggz',
    'penitentiare',
    'open', 
    'inrichting',
    'tehuis',
    'kazerne',
    'ademlucht',
    'aanvullen',
    'reset',
    'binnen',
    'bv',
    'gaarne',
    'ac',
    'th',
    'telcontact ',
    'berm/ruigte',
    'afval/rommel',
    'meting',
    'wegvervoer',
    'politie',
    'voertuigbrand',
    'voertuig',
    'dier',
    'dieren',
    'koe',
    'paard',
    'koeien',
    'paarden',
    'schaap',
    'schapen',
    'pony',
    'persoon',
    'water',
    'ass.',
    'ass',
    'ambu',
    'container',
    'ongeval',
    'thv',
    'hv',
    'beknelling',
    'hulp/dienstverlening',
    'auto',
    'trein',
    'drenkeling',
    'ambulance',
    'boom',
    'bomen',
    'hulp',
    'dienstverlening',
    'liftinsluiting',
    'liftopsluiting',
    'lift',
    'letsel',
    'wateroverlast',
    'hulpverlening',
    'brand',
    'buitenbrand',
    'buitensluiting',
    'binnenbrand',
    'brandmelding',
    'brandgerucht',
    'gebouwbrand',
    'middelbrand',
    'brandlucht',
    'test',
    'testen',
    'oefening',
    'vervalt',
    'vervallen',
    'controle',
    'vreemde',
    'lucht',
    'nacontrole',
    'oms',
    'pac',
    'stormschade',
    'woning',
    'op',
    'hoogte',
    'te',
    'luchtvaart',
    'Rook/CO',
    'melder',
    'materieel',
    'to',
    'die',
    'Buijtenweije',
    'snow',
    'world',
    'ambu/politie',
    'politiebureau',
    'verpleeghuis',
    'tel',
    'telefonisch',
    'rac',
    'contact',
    'voor',
    'vertrek',
    'karwei',
    'praxis',
    'gamma',
    'ikea',
);

$afkortingen = array(
    'DHG'=> 'Den Haag',
    'HLM'=> 'Hillegom',
    'WSR'=> 'Wassenaar',
    'LSE' => 'Lisse',
    'LSM' => 'Leidschendam',
    'VBG' => 'Voorburg',
    'SSM' => 'Sassenheim',
    'SHT' => 'Stadshart',
    'WMD' => 'Warmond',
    'OEM' => 'Oosterheem',
    'VHT' => 'Voorhout',
    'PAP' => 'Pijnacker-Nootdorp',
    'NDP' => 'Pijnacker-Nootdorp',
    'RBG' => 'Rijnsburg',
    'DLT' => 'Delft',
    'VKG' => 'Valkenburg',
    'RSK' => 'Rijswijk',
    'RIJK' => 'Rijswijk',
    'KWK' => 'Katwijk',
    'NWK' => 'Noordwijk',
    'NWT' => 'Noordwijkerhout',
    'DHN' => 'Den Hoorn',
    'DGW' => 'Delfgauw',
    'SLN' => 'Schipluiden',
    'MLD' => 'Maasland',
    'KAG' => 'Kaag',
    'MDK' => 'Maasdijk',
    'RLN' => 'Roelofarendsveen',
    'NAK' => 'Naaldwijk',
    'LMN' => 'Leimuiden',
    'GVE' => 's Gravenzand',
    'WBE' => 'Woubrugge',
    'HSK' => 'Honselersdijk',
    'RWG' => 'Rijpwetering',
    'MNR' => 'Monster',
    'NVN' => 'Nieuwveen',
    'WTN' => 'Wateringen',
    'NKP' => 'Nieuwkoop',
    'DLR' => 'De Lier',
    'TAR' => 'Ter Aar',
    'ALN' => 'Aarlanderveen',
    'ZMM' => 'Zwammerdam',
    'SVN' => 'Scheveningen',
    'APN' => 'Alphen ad Rijn',
    'ACL' => 'Archipel',
    'BKP' => 'Boskoop',
    'HST' => 'Haagse Hout',
    'BHN' => 'Benthuizen',
    'LSN' => 'Leidscheveen',
    'HZE' => 'Hazerswoude',
    'LAK' => 'Laak',
    'KDK' => 'Koudekerk',
    'LSD' => 'Loosduinen',
    'CTM' => 'Centrum',
    'BDN' => 'Bodegraven',
    'NBG' => 'Nieuwerbrug',
    'DBN' => 'Driebruggen',
    'RWK' => 'Reeuwijk',
    'GDA' => 'Gouda',
    'HTT' => 'Haastrecht',
    'SWK' => 'Stolwijk',
    'SHN' => 'Schoonhoven',
    'BAT' => 'Bergambacht',
    'LKK' => 'Lekkerkerk',
    'KAL' => 'Krimpen ad Lek',
    'OAY' => 'Ouderkerk ad IJssel',
    'GDK' => 'Gouderak',
    'MDT' => 'Moordrecht',
    'NAY' => 'Nieuwerkerk ad IJssel',
    'ZHN' => 'Zevenhuizen',
    'WDN' => 'Waddinxveen',
    'OGT' => 'Oegstgeest',
    'LDN' => 'Leiden Noord',
    'LDZ' => 'Leiden Zuid',
    'LDP' => 'Leiderdorp',
    'VSN' => 'Voorschoten',
    'ZTR' => 'Zoetermeer',
);